// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Analysis struct {
	ID           int32            `json:"id"`
	DateTime     pgtype.Timestamp `json:"date_time"`
	Product      pgtype.Text      `json:"product"`
	ColorRhs     pgtype.Text      `json:"color_rhs"`
	IDUser       pgtype.Text      `json:"id_user"`
	TelegramLink pgtype.Text      `json:"telegram_link"`
	Text         pgtype.Text      `json:"text"`
	FileSource   pgtype.Text      `json:"file_source"`
	ScaleMmPixel pgtype.Float8    `json:"scale_mm_pixel"`
	Mass         pgtype.Float8    `json:"mass"`
	Area         pgtype.Float8    `json:"area"`
	R            []byte           `json:"r"`
	G            []byte           `json:"g"`
	B            []byte           `json:"b"`
	H            []byte           `json:"h"`
	S            []byte           `json:"s"`
	V            []byte           `json:"v"`
	LabL         []byte           `json:"lab_l"`
	LabA         []byte           `json:"lab_a"`
	LabB         []byte           `json:"lab_b"`
	W            []byte           `json:"w"`
	L            []byte           `json:"l"`
	T            []byte           `json:"t"`
	FileOutput   pgtype.Text      `json:"file_output"`
	IDAnalysis   pgtype.Text      `json:"id_analysis"`
}

type Object struct {
	ID         int32         `json:"id"`
	IDAnalysis pgtype.Int8   `json:"id_analysis"`
	File       pgtype.Text   `json:"file"`
	MH         pgtype.Float8 `json:"m_h"`
	MS         pgtype.Float8 `json:"m_s"`
	MV         pgtype.Float8 `json:"m_v"`
	MR         pgtype.Float8 `json:"m_r"`
	MG         pgtype.Float8 `json:"m_g"`
	MB         pgtype.Float8 `json:"m_b"`
	LAvg       pgtype.Float8 `json:"l_avg"`
	WAvg       pgtype.Float8 `json:"w_avg"`
	BrtAvg     pgtype.Float8 `json:"brt_avg"`
	RAvg       pgtype.Float8 `json:"r_avg"`
	GAvg       pgtype.Float8 `json:"g_avg"`
	BAvg       pgtype.Float8 `json:"b_avg"`
	HAvg       pgtype.Float8 `json:"h_avg"`
	SAvg       pgtype.Float8 `json:"s_avg"`
	VAvg       pgtype.Float8 `json:"v_avg"`
	H          pgtype.Float8 `json:"h"`
	S          pgtype.Float8 `json:"s"`
	V          pgtype.Float8 `json:"v"`
	HM         pgtype.Float8 `json:"h_m"`
	SM         pgtype.Float8 `json:"s_m"`
	VM         pgtype.Float8 `json:"v_m"`
	RM         pgtype.Float8 `json:"r_m"`
	GM         pgtype.Float8 `json:"g_m"`
	BM         pgtype.Float8 `json:"b_m"`
	BrtM       pgtype.Float8 `json:"brt_m"`
	WM         pgtype.Float8 `json:"w_m"`
	LM         pgtype.Float8 `json:"l_m"`
	L          pgtype.Float8 `json:"l"`
	W          pgtype.Float8 `json:"w"`
	LW         pgtype.Float8 `json:"l_w"`
	Pr         pgtype.Float8 `json:"pr"`
	Sq         pgtype.Float8 `json:"sq"`
	Brt        pgtype.Float8 `json:"brt"`
	R          pgtype.Float8 `json:"r"`
	G          pgtype.Float8 `json:"g"`
	B          pgtype.Float8 `json:"b"`
	Solid      pgtype.Float8 `json:"solid"`
	MinH       pgtype.Float8 `json:"min_h"`
	MinS       pgtype.Float8 `json:"min_s"`
	MinV       pgtype.Float8 `json:"min_v"`
	MaxH       pgtype.Float8 `json:"max_h"`
	MaxS       pgtype.Float8 `json:"max_s"`
	MaxV       pgtype.Float8 `json:"max_v"`
	Entropy    pgtype.Float8 `json:"entropy"`
	IDImage    pgtype.Int8   `json:"id_image"`
	ColorRhs   pgtype.Text   `json:"color_rhs"`
	Geometry   pgtype.Text   `json:"geometry"`
	SqSqcrl    pgtype.Float8 `json:"sq_sqcrl"`
	Hu1        pgtype.Float8 `json:"hu1"`
	Hu2        pgtype.Float8 `json:"hu2"`
	Hu3        pgtype.Float8 `json:"hu3"`
	Hu4        pgtype.Float8 `json:"hu4"`
	Hu5        pgtype.Float8 `json:"hu5"`
	Hu6        pgtype.Float8 `json:"hu6"`
	Class      pgtype.Text   `json:"class"`
}
