// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAnalysesByUserID(ctx context.Context, arg CountAnalysesByUserIDParams) (int64, error)
	GetAnalysesByIDs(ctx context.Context, ids []int32) ([]Analysis, error)
	GetAnalysesByUserTelegramIDPagination(ctx context.Context, arg GetAnalysesByUserTelegramIDPaginationParams) ([]Analysis, error)
	// Queries for the analysis table
	GetAnalysisByID(ctx context.Context, idAnalysis pgtype.Text) (Analysis, error)
	// Queries for the objects table
	GetObjectByID(ctx context.Context, id int32) (Object, error)
	GetObjectsByAnalysisID(ctx context.Context, analysisID pgtype.Int8) ([]Object, error)
	GetObjectsByIDs(ctx context.Context, ids []int32) ([]GetObjectsByIDsRow, error)
	GetObjectsImages(ctx context.Context, ids []int32) ([]GetObjectsImagesRow, error)
	GetObjectsImagesForAnalysis(ctx context.Context, idAnalysis pgtype.Int8) ([]GetObjectsImagesForAnalysisRow, error)
	GetObjectsMetadata(ctx context.Context, ids []int32) ([]GetObjectsMetadataRow, error)
	GetObjectsMetadataForAnalysis(ctx context.Context, idAnalysis pgtype.Int8) ([]GetObjectsMetadataForAnalysisRow, error)
}

var _ Querier = (*Queries)(nil)
